const QUESTIONS = [
// OBJECTIVE — foundations
{id:1,type:'objective',q:'Which statement best defines a project?',o:['A continuous repetitive operation','A temporary undertaking that creates a unique result','A permanent department','A routine accounting process'],a:1,e:'A project is temporary and creates a unique product, service or result.'},
{id:2,type:'objective',q:'Which characteristic most clearly distinguishes a project from routine operations?',o:['It uses resources','It has a manager','It is temporary and unique','It requires communication'],a:2,e:'Projects have a definite beginning/end and a unique outcome.'},
{id:3,type:'objective',q:'Project management is primarily concerned with:',o:['Only controlling employees','Applying knowledge, skills, tools and techniques to project activities','Preparing annual payroll','Eliminating all organizational risk'],a:1,e:'Project management coordinates methods and resources to meet project requirements.'},
{id:4,type:'objective',q:'Which is NOT normally a project constraint?',o:['Time','Cost','Scope','Employee surname'],a:3,e:'Time, cost and scope are classic constraints; employee surname is not.'},
{id:5,type:'objective',q:'A project should normally begin with:',o:['Final evaluation','Problem, need or opportunity identification','Contract closure','Staff release'],a:1,e:'Projects originate from an identified need, problem or opportunity.'},
{id:6,type:'objective',q:'Which is an example of a project?',o:['Daily hospital operations','Weekly payroll processing','Construction of a new hospital','Routine customer service'],a:2,e:'Construction has a defined start/end and unique deliverable.'},
{id:7,type:'objective',q:'A project deliverable is:',o:['A measurable product, service or result produced by a project','A staff attendance sheet only','A project rumor','An unapproved idea'],a:0,e:'Deliverables are tangible or verifiable outputs/results.'},
{id:8,type:'objective',q:'A milestone is best described as:',o:['A project employee','A significant point or event in a project schedule','A budget deficit','A risk response'],a:1,e:'Milestones mark important events or achievements.'},
{id:9,type:'objective',q:'Project scope defines:',o:['Only project salaries','The boundaries of work and deliverables included in the project','Only the project location','Only procurement rules'],a:1,e:'Scope establishes what is included and excluded.'},
{id:10,type:'objective',q:'Scope creep refers to:',o:['Reducing project requirements','Uncontrolled expansion of project requirements','Closing a project early','Completing a project under budget'],a:1,e:'Scope creep is uncontrolled growth in project scope without proper change control.'},
// objectives — life cycle and identification
{id:11,type:'objective',q:'Which sequence best represents a typical project life cycle?',o:['Closure → initiation → execution → planning','Initiation → planning → execution → monitoring/control → closure','Planning → closure → initiation → execution','Execution → initiation → closure → planning'],a:1,e:'This is the conventional high-level sequence.'},
{id:12,type:'objective',q:'Project identification focuses primarily on:',o:['Recognizing a problem, need or opportunity','Closing procurement contracts','Calculating final profit','Releasing all staff'],a:0,e:'Identification establishes the development or organizational need for a project.'},
{id:13,type:'objective',q:'Which is a source of project ideas?',o:['Community needs','Research findings','Government policies','All of the above'],a:3,e:'All listed sources can generate legitimate project ideas.'},
{id:14,type:'objective',q:'Project selection answers which question?',o:['Which possible project should be undertaken?','Who invented project management?','What is an employee salary?','When should payroll be processed?'],a:0,e:'Selection chooses among competing project alternatives.'},
{id:15,type:'objective',q:'Project prioritization is especially necessary when:',o:['Resources are unlimited','There are competing projects and limited resources','No project exists','No objectives have been defined'],a:1,e:'Prioritization allocates scarce resources to the most valuable alternatives.'},
{id:16,type:'objective',q:'Which factor may be used to prioritize projects?',o:['Strategic importance','Expected benefits','Risk','All of the above'],a:3,e:'Strategic value, benefits and risk are common prioritization criteria.'},
{id:17,type:'objective',q:'A feasibility study primarily determines whether a proposed project is:',o:['Popular on social media','Practical and viable','Already completed','Free of every possible risk'],a:1,e:'Feasibility examines whether the proposal can reasonably be implemented.'},
{id:18,type:'objective',q:'Technical feasibility examines:',o:['Whether technology, expertise and infrastructure are available','Only community opinions','Only taxation','Only staff uniforms'],a:0,e:'Technical feasibility assesses technical capability and requirements.'},
{id:19,type:'objective',q:'Financial feasibility is concerned mainly with:',o:['Whether the project can be financially supported','Whether the project has a logo','Whether staff like the project','Whether the project has a title'],a:0,e:'It assesses financial requirements, funding and affordability.'},
{id:20,type:'objective',q:'Legal feasibility asks whether:',o:['The project can comply with relevant laws and regulations','The project has enough chairs','The project has a website','The project has a slogan'],a:0,e:'Legal feasibility assesses regulatory and legal compliance.'},
{id:21,type:'objective',q:'Environmental feasibility focuses on:',o:['Environmental consequences of the project','Employee promotion','Payroll processing','Office decoration'],a:0,e:'It examines environmental effects and requirements.'},
{id:22,type:'objective',q:'Operational feasibility examines whether:',o:['The organization can operate and sustain the project output','The project has the longest title','The contractor owns a phone','The budget is handwritten'],a:0,e:'Operational feasibility considers organizational capacity to use and sustain outputs.'},
{id:23,type:'objective',q:'Project appraisal occurs primarily to:',o:['Assess a proposed project before major resources are committed','Close the project','Replace all stakeholders','Avoid planning'],a:0,e:'Appraisal supports rational investment and approval decisions.'},
{id:24,type:'objective',q:'Cost-benefit analysis compares:',o:['Project benefits with project costs','Employee names with salaries','Risks with meetings','Scope with logos'],a:0,e:'CBA evaluates whether benefits justify costs.'},
{id:25,type:'objective',q:'Under a basic financial cost-benefit decision rule, a project is generally attractive when:',o:['Costs exceed benefits','Benefits exceed relevant costs','No benefits exist','The schedule is unknown'],a:1,e:'Positive net benefits support acceptance, subject to other considerations.'},
// objectives — appraisal
{id:26,type:'objective',q:'The basic Payback Period measures:',o:['Time required to recover an initial investment','Total project quality','Stakeholder power','Number of employees'],a:0,e:'Payback measures investment recovery time.'},
{id:27,type:'objective',q:'If an investment is ₦10 million and annual cash inflow is ₦2 million, simple payback is:',o:['2 years','5 years','10 years','20 years'],a:1,e:'₦10m ÷ ₦2m = 5 years.'},
{id:28,type:'objective',q:'A major limitation of basic Payback Period is that it:',o:['Always uses NPV','May ignore the time value of money and post-payback cash flows','Cannot be calculated','Measures stakeholder satisfaction'],a:1,e:'Simple payback has important cash-flow and time-value limitations.'},
{id:29,type:'objective',q:'NPV stands for:',o:['Net Project Variation','Net Present Value','New Procurement Value','National Project Volume'],a:1,e:'NPV means Net Present Value.'},
{id:30,type:'objective',q:'A positive NPV generally indicates that:',o:['Present value of inflows exceeds present value of outflows','The project must be rejected','The project has no cash flows','The project has zero cost'],a:0,e:'Positive NPV indicates value creation relative to the chosen discount rate.'},
{id:31,type:'objective',q:'IRR is the rate at which:',o:['Project duration becomes zero','NPV equals zero','All risks disappear','Scope becomes unlimited'],a:1,e:'IRR is the discount rate that sets NPV to zero.'},
{id:32,type:'objective',q:'If IRR is greater than the required rate of return, a project is generally:',o:['Financially acceptable','Automatically impossible','Always rejected','Already closed'],a:0,e:'IRR above the hurdle rate generally supports acceptance.'},
// objectives — planning, WBS, schedule
{id:33,type:'objective',q:'Project planning determines:',o:['How project objectives will be achieved','Only employee salaries','Only project branding','Only project closure'],a:0,e:'Planning establishes scope, schedule, resources, cost, risks and approaches.'},
{id:34,type:'objective',q:'A good project objective should be SMART. The M stands for:',o:['Managed','Measurable','Modern','Mandatory'],a:1,e:'SMART = Specific, Measurable, Achievable, Relevant, Time-bound.'},
{id:35,type:'objective',q:'Which objective is most clearly SMART?',o:['Improve education','Build something soon','Construct a 20-classroom school within 18 months','Make the community happy'],a:2,e:'It identifies a specific deliverable and time limit.'},
{id:36,type:'objective',q:'A Work Breakdown Structure (WBS) is used to:',o:['Decompose project work into manageable components','Calculate employee tax only','Replace the project budget','Eliminate stakeholders'],a:0,e:'WBS organizes the total project scope into smaller components.'},
{id:37,type:'objective',q:'Which is a useful scheduling tool?',o:['Gantt chart','Payroll ledger','Telephone directory','Asset tag'],a:0,e:'Gantt charts visually map activities against time.'},
{id:38,type:'objective',q:'A Gantt chart primarily displays:',o:['Activities against time','Stakeholder personalities','Project laws','Only risks'],a:0,e:'Gantt charts show timing and duration of activities.'},
{id:39,type:'objective',q:'A dependency means:',o:['A logical relationship between project activities','A project employee','A type of budget','A quality certificate'],a:0,e:'Dependencies determine activity sequencing.'},
{id:40,type:'objective',q:'The Critical Path Method identifies:',o:['The longest-duration path that determines minimum project completion time','The cheapest supplier','The strongest stakeholder','The project logo'],a:0,e:'Critical path activities determine the schedule duration under CPM.'},
{id:41,type:'objective',q:'Activities on the critical path generally have:',o:['Zero total float','Unlimited float','No duration','No relationship'],a:0,e:'Under standard CPM, critical activities have zero total float.'},
{id:42,type:'objective',q:'PERT is particularly useful when:',o:['Activity durations are uncertain','There is no schedule','There are no activities','Only payroll is involved'],a:0,e:'PERT uses probabilistic time estimates.'},
{id:43,type:'objective',q:'PERT uses which three time estimates?',o:['Fast, slow, final','Optimistic, most likely, pessimistic','Cost, profit, tax','Start, middle, end'],a:1,e:'PERT uses O, M and P estimates.'},
{id:44,type:'objective',q:'The PERT expected-time formula is:',o:['(O+M+P)/3','(O+4M+P)/6','O×M×P','(O−M)+P'],a:1,e:'TE = (O + 4M + P) / 6.'},
{id:45,type:'objective',q:'If O=2, M=5 and P=8, PERT expected time is:',o:['3 days','5 days','8 days','15 days'],a:1,e:'(2 + 4×5 + 8)/6 = 5 days.'},
// objectives — resources/cost
{id:46,type:'objective',q:'Which is NOT a typical project resource?',o:['Human resources','Finance','Materials','A project rumor'],a:3,e:'Rumors are not a managed project resource.'},
{id:47,type:'objective',q:'Resource allocation means:',o:['Assigning available resources to project activities','Destroying resources','Avoiding all planning','Closing contracts'],a:0,e:'Allocation matches resources to tasks and timing.'},
{id:48,type:'objective',q:'Project cost management includes:',o:['Estimating, budgeting and controlling costs','Only paying salaries','Only buying equipment','Only auditing after closure'],a:0,e:'These are core cost-management activities.'},
{id:49,type:'objective',q:'A cost overrun occurs when:',o:['Actual cost exceeds approved/planned cost','Actual cost is lower than budget','No budget exists','A project finishes early'],a:0,e:'Cost overrun is expenditure above the relevant approved baseline.'},
{id:50,type:'objective',q:'Which can cause cost overruns?',o:['Poor estimation','Inflation','Scope changes','All of the above'],a:3,e:'Each can increase actual project cost.'},
// objectives — risk/stakeholders
{id:51,type:'objective',q:'A project risk is:',o:['An uncertain event or condition that may affect objectives','A guaranteed outcome','A completed deliverable','A project invoice'],a:0,e:'Risk concerns uncertainty and potential impact.'},
{id:52,type:'objective',q:'The first major step in risk management is:',o:['Risk identification','Risk closure','Staff dismissal','Contract payment'],a:0,e:'Risks must be identified before they can be analyzed and treated.'},
{id:53,type:'objective',q:'Risk mitigation means:',o:['Reducing probability or impact of a risk','Pretending a risk does not exist','Automatically cancelling the project','Increasing every project cost'],a:0,e:'Mitigation reduces likelihood and/or impact.'},
{id:54,type:'objective',q:'Risk transfer involves:',o:['Shifting responsibility or financial consequences to another party','Deleting all risks','Increasing scope','Ignoring stakeholders'],a:0,e:'Insurance and contractual arrangements can transfer risk.'},
{id:55,type:'objective',q:'Risk acceptance means:',o:['Recognizing a risk and deciding to manage its consequences if it occurs','Eliminating every risk','Guaranteeing project success','Changing the project title'],a:0,e:'Acceptance is a deliberate response when avoidance/mitigation/transfer is not justified.'},
{id:56,type:'objective',q:'A stakeholder is:',o:['Anyone who can affect, be affected by, or perceive themselves affected by a project','Only the project manager','Only the contractor','Only government'],a:0,e:'Stakeholder definition is broad and includes affected/interested parties.'},
{id:57,type:'objective',q:'In a power-interest matrix, stakeholders with high power and high interest should be:',o:['Managed closely','Ignored','Monitored only','Removed'],a:0,e:'High-power/high-interest stakeholders require close management.'},
{id:58,type:'objective',q:'High-power, low-interest stakeholders should generally be:',o:['Kept satisfied','Managed hourly','Ignored completely','Given project ownership'],a:0,e:'The matrix recommends keeping them satisfied.'},
{id:59,type:'objective',q:'Low-power, high-interest stakeholders should generally be:',o:['Kept informed','Ignored','Removed','Given unlimited authority'],a:0,e:'They have strong interest but limited power, so communication is important.'},
{id:60,type:'objective',q:'An internal stakeholder is most likely:',o:['A project employee or executive within the organization','A community member only','An external regulator only','A random customer'],a:0,e:'Internal stakeholders are within the organization.'},
// objectives — team, communication, procurement
{id:61,type:'objective',q:'The project manager primarily:',o:['Coordinates project activities and resources to achieve approved objectives','Works without a plan','Avoids stakeholders','Only signs attendance sheets'],a:0,e:'The project manager integrates delivery and coordination.'},
{id:62,type:'objective',q:'Which quality is especially important for a project manager?',o:['Integrity','Poor communication','Indecision','Avoidance'],a:0,e:'Integrity supports trust, accountability and ethical management.'},
{id:63,type:'objective',q:'Effective project communication helps to:',o:['Reduce misunderstanding and improve coordination','Hide project problems','Increase confusion','Eliminate reporting'],a:0,e:'Communication supports coordination, decisions and stakeholder confidence.'},
{id:64,type:'objective',q:'Which is a project communication artifact?',o:['Progress report','Payroll PIN','Personal diary only','Private rumor'],a:0,e:'Progress reports are formal project communication tools.'},
{id:65,type:'objective',q:'Project procurement involves:',o:['Obtaining goods, services or works required by the project','Only hiring employees permanently','Only evaluating risks','Only closing projects'],a:0,e:'Procurement obtains external goods, services and works.'},
{id:66,type:'objective',q:'Contract management focuses on:',o:['Ensuring contractual obligations are fulfilled','Avoiding all contracts','Writing personal letters','Removing all suppliers'],a:0,e:'Contract management monitors compliance and performance.'},
{id:67,type:'objective',q:'A conflict of interest is an ethical concern because:',o:['Personal interests may improperly influence professional decisions','It always improves transparency','It eliminates bias','It guarantees fairness'],a:0,e:'Conflicts can compromise impartial decision-making.'},
{id:68,type:'objective',q:'Project execution is the stage where:',o:['Planned activities are carried out','The idea is first invented','The final report is archived only','All stakeholders are dismissed'],a:0,e:'Execution converts plans into project work.'},
// objectives — monitoring/evaluation/quality/change/closure
{id:69,type:'objective',q:'Project monitoring involves:',o:['Continuous or periodic tracking of project performance','Only final celebrations','Only contract signing','Avoiding performance data'],a:0,e:'Monitoring collects and analyzes performance information.'},
{id:70,type:'objective',q:'Project control involves:',o:['Comparing actual performance with plans and taking corrective action','Ignoring deviations','Deleting the schedule','Ending every project'],a:0,e:'Control manages variance against approved plans/baselines.'},
{id:71,type:'objective',q:'Project evaluation is best described as:',o:['Systematic assessment of project relevance, effectiveness, efficiency, impact and sustainability','Daily attendance checking only','Procurement only','A project logo'],a:0,e:'Evaluation assesses project performance and results at appropriate points.'},
{id:72,type:'objective',q:'Quality control primarily involves:',o:['Inspecting/testing outputs against requirements','Writing project slogans','Hiring all stakeholders','Eliminating standards'],a:0,e:'Quality control checks outputs for conformity.'},
{id:73,type:'objective',q:'Quality assurance focuses on:',o:['Ensuring appropriate processes are being followed','Only checking the final product','Only calculating profit','Ignoring standards'],a:0,e:'QA is process-oriented and supports confidence in quality.'},
{id:74,type:'objective',q:'A proposed project change should normally be:',o:['Documented and analyzed for impact before approval','Accepted automatically','Hidden from stakeholders','Implemented without cost review'],a:0,e:'Change control assesses scope, cost, time, risk and quality implications.'},
{id:75,type:'objective',q:'Project closure should include:',o:['Formal acceptance, contract closure, resource release and lessons learned','Starting procurement again','Ignoring deliverables','Deleting records'],a:0,e:'Closure formally completes the project and captures learning.'},
{id:76,type:'objective',q:'Lessons learned are valuable because they:',o:['Transfer knowledge to future projects','Replace all planning','Guarantee no future risk','Eliminate documentation'],a:0,e:'Lessons learned improve organizational learning and future delivery.'},
{id:77,type:'objective',q:'Traditional project management is often characterized by:',o:['Sequential, plan-driven phases','No planning','Unlimited changes without control','No defined requirements'],a:0,e:'Traditional approaches commonly use planned sequential phases.'},
{id:78,type:'objective',q:'Agile project management emphasizes:',o:['Iteration, collaboration, feedback and adaptability','No stakeholder feedback','Fixed plans with no change','One final delivery only'],a:0,e:'Agile is adaptive and iterative.'},
{id:79,type:'objective',q:'The traditional triple constraint includes:',o:['Scope, time and cost','People, logo and office','Risk, lunch and salary','Quality, email and tax'],a:0,e:'Scope, schedule/time and cost are the classic triple constraint.'},
{id:80,type:'objective',q:'A project baseline is:',o:['An approved reference point for comparing actual performance','An employee biography','A risk only','A meeting invitation'],a:0,e:'Baselines support performance measurement and control.'},
// SUBJECTIVE — short answers
{id:81,type:'subjective',q:'In one or two sentences, define project management.',keys:['application','knowledge','skills','tools','techniques','project','requirements'],e:'Project management is the application of knowledge, skills, tools and techniques to project activities to meet requirements.'},
{id:82,type:'subjective',q:'State two characteristics of a project.',keys:['temporary','unique'],e:'Any two: temporary, unique, specific objective, limited resources, uncertainty, stakeholders.'},
{id:83,type:'subjective',q:'What is project identification?',keys:['problem','need','opportunity','identify'],e:'It is the process of recognizing a problem, need or opportunity that may be addressed by a project.'},
{id:84,type:'subjective',q:'Mention four sources of project ideas.',keys:['community','policy','research','market','problem','technology','customer'],e:'Examples: community needs, policies, research findings, market research, technology, organizational problems.'},
{id:85,type:'subjective',q:'What is a feasibility study?',keys:['practical','viable','proposed','project'],e:'A feasibility study assesses whether a proposed project is practical and viable.'},
{id:86,type:'subjective',q:'State four types of feasibility study.',keys:['technical','financial','legal','operational','environmental','social','economic'],e:'Examples include technical, financial, economic, legal, operational, environmental and social feasibility.'},
{id:87,type:'subjective',q:'What is cost-benefit analysis?',keys:['cost','benefit','compare','project'],e:'It compares expected project benefits with relevant project costs to support an investment decision.'},
{id:88,type:'subjective',q:'Define scope creep.',keys:['uncontrolled','expansion','scope','requirements'],e:'Scope creep is uncontrolled expansion of project requirements without proper change control.'},
{id:89,type:'subjective',q:'What does SMART mean in project objectives?',keys:['specific','measurable','achievable','relevant','time'],e:'Specific, Measurable, Achievable, Relevant, Time-bound.'},
{id:90,type:'subjective',q:'What is a Work Breakdown Structure?',keys:['decompose','work','manageable','components','project'],e:'WBS decomposes total project work/scope into smaller manageable components.'},
{id:91,type:'subjective',q:'Define the critical path.',keys:['longest','path','duration','project','completion'],e:'The critical path is the longest-duration path through the project network and determines minimum completion time.'},
{id:92,type:'subjective',q:'State the three PERT time estimates.',keys:['optimistic','most likely','pessimistic'],e:'Optimistic, most likely and pessimistic estimates.'},
{id:93,type:'subjective',q:'What is project risk?',keys:['uncertain','event','condition','affect','objectives'],e:'An uncertain event or condition that may positively or negatively affect project objectives.'},
{id:94,type:'subjective',q:'Mention four risk response strategies.',keys:['avoid','mitigate','transfer','accept'],e:'Avoid, mitigate, transfer and accept.'},
{id:95,type:'subjective',q:'Define a stakeholder.',keys:['individual','group','organization','affect','affected','project'],e:'An individual, group or organization that can affect, be affected by, or perceive itself affected by a project.'},
{id:96,type:'subjective',q:'What is project monitoring?',keys:['tracking','performance','project','activities','progress'],e:'Monitoring is the continuous or periodic tracking and analysis of project performance/progress.'},
{id:97,type:'subjective',q:'Differentiate monitoring from evaluation in one sentence.',keys:['monitoring','continuous','evaluation','assessment'],e:'Monitoring tracks progress during implementation; evaluation systematically assesses performance and results.'},
{id:98,type:'subjective',q:'What is project quality control?',keys:['inspect','test','outputs','requirements','standards'],e:'Quality control inspects or tests project outputs against defined requirements or standards.'},
{id:99,type:'subjective',q:'What is project closure?',keys:['formal','complete','project','acceptance','resources'],e:'Project closure formally completes the project, confirms acceptance, closes contracts and releases resources.'},
{id:100,type:'subjective',q:'State three responsibilities of a project manager.',keys:['planning','coordination','risk','cost','communication','quality','stakeholder','schedule'],e:'Examples: planning, coordinating resources, managing risk, cost, schedule, quality, stakeholders and communication.'},
// THEORY
{id:101,type:'theory',q:'Explain the major characteristics of a project and distinguish projects from routine operations.',keys:['temporary','unique','objective','operation','continuous'],e:'Discuss temporariness, uniqueness, objectives, limited resources and uncertainty; contrast these with continuous repetitive operations.'},
{id:102,type:'theory',q:'Discuss the principles of project management and explain why they are important.',keys:['planning','objective','scope','resource','communication','risk','quality','stakeholder','accountability'],e:'A strong answer should explain clear purpose/objectives, planning, scope, resource efficiency, communication, stakeholder engagement, risk, quality, monitoring, accountability and adaptability.'},
{id:103,type:'theory',q:'Explain the project life cycle from initiation to closure.',keys:['initiation','planning','execution','monitoring','control','closure'],e:'Explain initiation, planning, execution, monitoring/control and closure, including the major activities in each.'},
{id:104,type:'theory',q:'Discuss project identification and explain five sources of project ideas available to public organizations.',keys:['identification','community','policy','research','problem','technology','market'],e:'Define identification, then discuss sources such as community needs, government policy, research, organizational problems, technology and market/social needs.'},
{id:105,type:'theory',q:'Explain project feasibility studies and discuss five types.',keys:['feasibility','technical','financial','economic','legal','operational','environmental','social'],e:'Define feasibility and explain technical, financial, economic, legal, operational, environmental or social dimensions.'},
{id:106,type:'theory',q:'Compare Payback Period, NPV and IRR as project appraisal techniques.',keys:['payback','npv','irr','time','value','rate','cash'],e:'Explain each technique, decision rules, strengths and limitations; note that NPV explicitly incorporates time value of money.'},
{id:107,type:'theory',q:'Explain project planning and identify the major components of a comprehensive project plan.',keys:['scope','schedule','cost','resource','risk','quality','communication','procurement','stakeholder'],e:'Discuss planning and its components: scope, schedule, cost, resources, quality, risk, communications, procurement and stakeholders.'},
{id:108,type:'theory',q:'Explain the Work Breakdown Structure and its importance in project management.',keys:['wbs','decompose','scope','work','manageable','estimate','assign'],e:'Define WBS and explain decomposition, work packages, estimation, assignment, scheduling and control benefits.'},
{id:109,type:'theory',q:'Discuss Gantt charts, CPM and PERT as project scheduling techniques.',keys:['gantt','cpm','pert','schedule','critical','optimistic','pessimistic'],e:'Define each tool, explain use cases, advantages and limitations, including PERT uncertainty and CPM critical path.'},
{id:110,type:'theory',q:'Discuss project resource and cost management, including causes of cost overruns.',keys:['resource','cost','estimate','budget','control','overrun','inflation','scope'],e:'Cover resource planning/allocation, cost estimation, budgeting/control and causes such as poor estimates, inflation, delays and scope changes.'},
{id:111,type:'theory',q:'Explain the project risk management process and four risk response strategies.',keys:['identify','analyze','response','monitor','avoid','mitigate','transfer','accept'],e:'Explain identification, analysis, response planning and monitoring; discuss avoidance, mitigation, transfer and acceptance.'},
{id:112,type:'theory',q:'Define stakeholders and explain the power-interest matrix.',keys:['stakeholder','power','interest','closely','satisfied','informed','monitor'],e:'Define stakeholders and explain high/high, high/low, low/high and low/low management approaches.'},
{id:113,type:'theory',q:'Discuss the role, responsibilities and qualities of an effective project manager.',keys:['planning','leadership','communication','risk','cost','schedule','quality','integrity'],e:'Discuss planning, coordination, resources, risk, cost, schedule, quality, stakeholders, communication, leadership and integrity.'},
{id:114,type:'theory',q:'Explain project communication management and its importance.',keys:['communication','information','stakeholder','coordination','report','meeting','decision'],e:'Discuss communication channels, information flow, reports, meetings, stakeholder confidence, coordination and decision-making.'},
{id:115,type:'theory',q:'Discuss procurement and contract management in project implementation.',keys:['procurement','supplier','contractor','specification','evaluate','contract','performance'],e:'Explain requirements, specifications, procurement strategy, solicitation/evaluation, selection, contract award and performance monitoring.'},
{id:116,type:'theory',q:'Differentiate project monitoring from project evaluation and explain their importance.',keys:['monitoring','tracking','evaluation','assessment','performance','impact'],e:'Monitoring tracks performance during implementation; evaluation assesses relevance, effectiveness, efficiency, impact and sustainability.'},
{id:117,type:'theory',q:'Discuss project quality management, distinguishing quality planning, assurance and control.',keys:['quality','planning','assurance','control','standards','inspect','process'],e:'Explain quality planning, process-oriented assurance and output-oriented control.'},
{id:118,type:'theory',q:'Explain project change management and discuss how scope creep can be controlled.',keys:['change','scope','impact','approval','control','requirements','cost','time'],e:'Explain documenting, analyzing, approving and communicating changes; discuss formal change control to prevent uncontrolled scope expansion.'},
{id:119,type:'theory',q:'Discuss the major causes of project failure, with particular reference to public projects.',keys:['planning','funding','corruption','procurement','political','monitoring','risk','contractor'],e:'Discuss poor planning, funding delays, corruption, procurement problems, political interference, weak monitoring, poor risk management and contractor issues.'},
{id:120,type:'theory',q:'Discuss the importance of project management in public administration and the challenges of managing public projects in Nigeria.',keys:['public','administration','accountability','transparency','service','infrastructure','funding','corruption','political','maintenance'],e:'Link project management to public service delivery, accountability and infrastructure; discuss funding, inflation, corruption, politics, procurement, insecurity, monitoring and maintenance challenges.'}
];

const state={user:null,exam:null,timer:null,result:null};
const $=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function getUsers(){return JSON.parse(localStorage.getItem('pm_users')||'{}')}
function saveUsers(u){localStorage.setItem('pm_users',JSON.stringify(u))}
function currentUser(){const n=localStorage.getItem('pm_current');if(!n)return null;const u=getUsers();return u[n]||null}
function show(id){$(id).classList.remove('hidden')};function hide(id){$(id).classList.add('hidden')}
function openAuth(mode='login'){show('authModal');switchTab(mode)}
function closeAuth(){hide('authModal')}
function switchTab(mode){$('loginTab').classList.toggle('active',mode==='login');$('registerTab').classList.toggle('active',mode==='register');$('loginForm').classList.toggle('hidden',mode!=='login');$('registerForm').classList.toggle('hidden',mode!=='register')}
function init(){
  $('loginTop').onclick=()=>openAuth('login');$('registerTop').onclick=()=>openAuth('register');$('heroLogin').onclick=()=>openAuth('login');$('heroRegister').onclick=()=>openAuth('register');
  document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeAuth);$('loginTab').onclick=()=>switchTab('login');$('registerTab').onclick=()=>switchTab('register');
  $('loginForm').onsubmit=e=>{e.preventDefault();const name=$('loginUsername').value.trim().toLowerCase(),pass=$('loginPassword').value;const u=getUsers();if(!u[name]||u[name].password!==pass)return toast('Invalid username or password.');localStorage.setItem('pm_current',name);closeAuth();loadUser();toast('Login successful.');};
  $('registerForm').onsubmit=e=>{e.preventDefault();const full=$('regName').value.trim(),name=$('regUsername').value.trim().toLowerCase(),pass=$('regPassword').value,confirm=$('regConfirm').value;if(pass!==confirm)return toast('Passwords do not match.');const u=getUsers();if(u[name])return toast('Username already exists.');u[name]={fullName:full,username:name,password:pass,created:new Date().toISOString(),history:[]};saveUsers(u);localStorage.setItem('pm_current',name);closeAuth();loadUser();toast('Account created successfully.');};
  $('logoutBtn').onclick=()=>{localStorage.removeItem('pm_current');state.user=null;hide('dashboard');hide('exam');hide('result');show('landing');$('loginTop').classList.remove('hidden');$('registerTop').classList.remove('hidden');$('userBadge').classList.add('hidden');};
  $('startExam').onclick=startExam;$('prevBtn').onclick=()=>move(-1);$('nextBtn').onclick=()=>move(1);$('submitBtn').onclick=()=>finishExam(false);$('reviewBtn').onclick=()=>{show('reviewPanel');renderReview()};$('closeReview').onclick=()=>hide('reviewPanel');$('newExamBtn').onclick=()=>{hide('result');show('dashboard');window.scrollTo({top:0,behavior:'smooth'});};$('clearHistory').onclick=clearHistory;
  $('sectionSelect').onchange=populateCounts;populateCounts();renderCoverage();
  const u=currentUser();if(u){loadUser()}else{show('landing');hide('dashboard');}
}
function loadUser(){state.user=currentUser();if(!state.user)return;hide('landing');hide('exam');hide('result');show('dashboard');$('studentName').textContent=state.user.fullName;$('userBadge').textContent='Student: '+state.user.fullName;$('userBadge').classList.remove('hidden');$('loginTop').classList.add('hidden');$('registerTop').classList.add('hidden');renderHistory();window.scrollTo({top:0,behavior:'smooth'})}
function filtered(section){return section==='all'?QUESTIONS:[...QUESTIONS].filter(x=>x.type===section)}
function populateCounts(){const arr=filtered($('sectionSelect').value);const s=$('countSelect');s.innerHTML='';[10,20,30,40,50,60,80,100,arr.length].filter((x,i,a)=>x<=arr.length&&a.indexOf(x)===i).forEach(n=>{const o=document.createElement('option');o.value=n;o.textContent=`${n} Questions`;s.appendChild(o)});if(arr.length>100)s.value=100;}
function renderCoverage(){const c=$('coverage');const counts={objective:0,subjective:0,theory:0};QUESTIONS.forEach(q=>counts[q.type]++);c.innerHTML=Object.entries(counts).map(([k,v])=>`<div class="coverage-item"><span>${k[0].toUpperCase()+k.slice(1)} Questions</span><b>${v}</b></div>`).join('')+'<div class="coverage-item"><span>Total Question Bank</span><b>'+QUESTIONS.length+'</b></div>'}
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function startExam(){const section=$('sectionSelect').value,count=Number($('countSelect').value),time=Number($('timeSelect').value);let qs=shuffle(filtered(section)).slice(0,count).map(q=>({...q,options:q.o?shuffle(q.o.map((text,i)=>({text,correct:i===q.a}))):null,answer:null}));state.exam={section,count,time,questions:qs,index:0,start:Date.now()};hide('dashboard');hide('result');show('exam');$('examSection').textContent=section==='all'?'MIXED EXAM':section.toUpperCase();$('examTitle').textContent='Principles of Project Management — CBT Practice';if(time){startTimer(time*60)}else{$('timer').textContent='Practice Mode';state.timer=null}renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}
function startTimer(seconds){clearInterval(state.timer);let remain=seconds;const tick=()=>{const m=Math.floor(remain/60),s=remain%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;$('timer').classList.toggle('warning',remain<=60);if(remain<=0){clearInterval(state.timer);finishExam(true)}remain--};tick();state.timer=setInterval(tick,1000)}
function renderQuestion(){const ex=state.exam,q=ex.questions[ex.index];$('questionType').textContent=q.type;$('questionNumber').textContent=`Question ${ex.index+1} of ${ex.questions.length}`;$('questionText').textContent=q.q;$('progressText').textContent=`Question ${ex.index+1} of ${ex.questions.length}`;const answered=ex.questions.filter(x=>x.answer!==null).length;$('answeredText').textContent=`${answered} answered`;$('progressBar').style.width=((ex.index+1)/ex.questions.length*100)+'%';renderNav();const area=$('answerArea');area.innerHTML='';if(q.type==='objective'){q.options.forEach((op,i)=>{const label=document.createElement('label');label.className='option'+(q.answer===i?' selected':'');label.innerHTML=`<input type="radio" name="ans" ${q.answer===i?'checked':''}> <span>${esc(op.text)}</span>`;label.onclick=()=>{q.answer=i;renderQuestion()};area.appendChild(label)})}else{const ta=document.createElement('textarea');ta.className='answer-input';ta.placeholder=q.type==='theory'?'Write your structured theory answer here…':'Write a concise answer here…';ta.value=q.answer||'';ta.oninput=e=>q.answer=e.target.value;area.appendChild(ta);const r=document.createElement('div');r.className='rubric';r.innerHTML='<b>Educational marking:</b> keyword-based automatic scoring is used for practice. A lecturer should review subjective/theory answers for formal grading.';area.appendChild(r)}$('prevBtn').disabled=ex.index===0;$('nextBtn').classList.toggle('hidden',ex.index===ex.questions.length-1);$('submitBtn').classList.toggle('hidden',ex.index!==ex.questions.length-1)}
function renderNav(){const g=$('questionGrid');g.innerHTML=state.exam.questions.map((q,i)=>`<button class="qnum ${q.answer!==null&&q.answer!==''?'answered':''} ${i===state.exam.index?'current':''}">${i+1}</button>`).join('');[...g.children].forEach((b,i)=>b.onclick=()=>{state.exam.index=i;renderQuestion()})}
function move(dir){state.exam.index=Math.max(0,Math.min(state.exam.questions.length-1,state.exam.index+dir));renderQuestion()}
function scoreText(q){if(q.type==='objective'){const ok=q.answer!==null&&q.options[q.answer]?.correct;return {score:ok?1:0,max:1,status:ok?'correct':'incorrect',answer:q.answer===null?'Not answered':q.options[q.answer].text}}const text=(q.answer||'').toLowerCase();const hits=(q.keys||[]).filter(k=>text.includes(k.toLowerCase()));const ratio=(q.keys||[]).length?hits.length/q.keys.length:0;let score=ratio>=.6?1:ratio>=.3?.5:0;return {score,max:1,status:score===1?'correct':score>0?'pending':'incorrect',answer:q.answer||'Not answered',hits:hits.length}} 
function finishExam(auto){if(!state.exam)return;const unanswered=state.exam.questions.filter(q=>q.answer===null||q.answer==='').length;if(!auto&&unanswered>0&&!confirm(`You have ${unanswered} unanswered question(s). Submit anyway?`))return;clearInterval(state.timer);const scored=state.exam.questions.map(scoreText);const total=scored.reduce((a,x)=>a+x.score,0),max=scored.length;const percent=Math.round(total/max*100);state.result={...state.exam,scored,total,max,percent};const u=getUsers();u[state.user.username].history.unshift({date:new Date().toISOString(),section:state.exam.section,count:max,percent,correct:scored.reduce((a,x)=>a+(x.score===1?1:0),0)});u[state.user.username].history=u[state.user.username].history.slice(0,10);saveUsers(u);hide('exam');show('result');$('scorePercent').textContent=percent+'%';$('correctCount').textContent=scored.filter(x=>x.score===1).length;$('wrongCount').textContent=scored.filter(x=>x.score===0).length;$('totalCount').textContent=max;$('resultTitle').textContent=auto?'Time Expired — Result':'Your Examination Result';renderSectionResults();hide('reviewPanel');window.scrollTo({top:0,behavior:'smooth'})}
function renderSectionResults(){const groups={objective:[],subjective:[],theory:[]};state.result.questions.forEach((q,i)=>groups[q.type].push(state.result.scored[i]));$('sectionResults').innerHTML=Object.entries(groups).filter(([,v])=>v.length).map(([k,v])=>{const p=Math.round(v.reduce((a,x)=>a+x.score,0)/v.length*100);return `<div class="section-result"><b>${k[0].toUpperCase()+k.slice(1)} — ${p}%</b><span>${v.length} questions • ${v.filter(x=>x.score===1).length} fully correct</span></div>`}).join('')}
function renderReview(){const ex=state.result;$('reviewList').innerHTML=ex.questions.map((q,i)=>{const s=ex.scored[i];const correct=q.type==='objective'?q.options.find(o=>o.correct)?.text:q.e;return `<div class="review-item"><h4>${i+1}. ${esc(q.q)}</h4><div class="your ${s.status}"><b>Your answer:</b> ${esc(s.answer)}</div><div><small><b>Expected/Reference:</b> ${esc(correct)}</small></div><div><small>Result: ${s.status==='correct'?'Correct':s.status==='pending'?'Partially matched':'Incorrect'}</small></div></div>`}).join('')}
function renderHistory(){const h=state.user.history||[];$('history').innerHTML=h.length?h.map(x=>`<div class="history-row"><strong>${esc(x.section==='all'?'Mixed Exam':x.section)}</strong><span>${x.count} questions</span><span>${x.correct} correct</span><b>${x.percent}%</b></div>`).join(''):'<div class="history-empty">No completed examinations yet. Start a practice exam to build your result history.</div>'}
function clearHistory(){const u=getUsers();u[state.user.username].history=[];saveUsers(u);state.user=currentUser();renderHistory();toast('Result history cleared.')}
init();
